export const SET_LIVING_ROOM = "SET_LIVING_ROOM";

export const SET_UNREAD_MESSAGES = "SET_UNREAD_MESSAGES";
export const SET_ACCUMULATOR_TO_INITIAL_UNREAD_MESSAGES =
  "SET_ACCUMULATOR_TO_INITIAL_UNREAD_MESSAGES";
export const SET_RESET_UNREAD_MESSAGES = "SET_RESET_UNREAD_MESSAGES";

export const SET_USER_MEDIA = "SET_USER_MEDIA";
export const SET_SUCCESS_TOAST = "SET_SUCCESS_TOAST";
export const SET_ERROR_TOAST = "SET_ERROR_TOAST";
export const SET_WARN_TOAST = "SET_WARN_TOAST";
export const SET_INFO_TOAST = "SET_INFO_TOAST";
export const SET_RESET_TOAST = "SET_RESET_TOAST";
export const SET_PROFILE = "SET_PROFILE";
export const RESET_PROFILE = "RESET_PROFILE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_FAVORITE_STREAMS = "UPDATE_FAVORITE_STREAMS";
export const LOGOUT_USER = "LOGOUT_USER";

export const SET_STREAMS_REDUX = "SET_STREAMS_REDUX";
export const SET_VLRS_REDUX = "SET_VLRS_REDUX";
export const UPDATE_STREAMS = "UPDATE_STREAMS";
export const ADD_STREAMS = "ADD_STREAMS";
export const ADD_STREAM = "ADD_STREAM";
export const UPDATE_STREAM = "UPDATE_STREAM";
export const REMOVE_STREAM = "REMOVE_STREAM";
export const UPDATE_VLRS = "UPDATE_VLRS";
export const UPDATE_STREAM_STATE = "UPDATE_STREAM_STATE";
export const UPDATE_STREAM_VLR_PREVIEW = "UPDATE_STREAM_VLR_PREVIEW";
export const SET_BROADCAST_OPTION = "SET_BROADCAST_OPTION";
export const SET_CHANNELS_SEARCH = "SET_CHANNELS_SEARCH";

export const SET_APP_CONFIG = "SET_APP_CONFIG";

export const SET_SHARED_SITE_DATA = "SET_SHARED_SITE_DATA";

export const SET_ROOM_LAYOUT = "SET_ROOM_LAYOUT";

export const STREAM_LOADING_START = "STREAM_LOADING_START";
export const STREAM_LOADING_DONE = "STREAM_LOADING_DONE";
export const STREAM_RECONNECTING = "STREAM_RECONNECTING";

export const SET_DEVICE_INFO = "SET_DEVICE_INFO";
export const SET_NETWORK_CONFIG = "SET_NETWORK_CONFIG";
export const SET_NETWORK_DATA = "SET_NETWORK_DATA";

export const SET_IN_APP_PRODUCTS = "SET_IN_APP_PRODUCTS";
export const UPDATE_IN_APP_PRODUCT = "UPDATE_IN_APP_PRODUCT";
export const UPDATE_IN_APP_OWNER = "UPDATE_IN_APP_OWNER";
export const REMOVE_IN_APP_OWNER = "REMOVE_IN_APP_OWNER";

export const STREAM_DEBUG_SET_SENT_STREAM = "STREAM_DEBUG_SET_SENT_STREAM";
export const STREAM_DEBUG_SET_REPLACE_SENT_STREAM =
  "STREAM_DEBUG_SET_REPLACE_SENT_STREAM";
export const STREAM_DEBUG_SET_RECEIVED_STREAM =
  "STREAM_DEBUG_SET_RECEIVED_STREAM";
export const STREAM_DEBUG_SET_VIDEO_ELEMENT = "STREAM_DEBUG_SET_VIDEO_ELEMENT";
export const STREAM_DEBUG_SET_HLS_ERROR = "STREAM_DEBUG_SET_HLS_ERROR";
export const STREAM_DEBUG_RESET_VALUES = "STREAM_DEBUG_RESET_VALUES";
export const STREAM_DEBUG_VERTO_SESSION = "STREAM_DEBUG_VERTO_SESSION";

export const SET_PREV_ROUTE = "SET_PREV_ROUTE";

export const PATCH_SELECTED_VLR_TEMPLATE = "PATCH_SELECTED_VLR_TEMPLATE";
export const RESET_SELECTED_VLR_TEMPLATE = "RESET_SELECTED_VLR_TEMPLATE";
export const ADD_VLR_TEMPLATE = "ADD_VLR_TEMPLATE";
export const SET_SELECTED_VLR_TEMPLATE = "SET_SELECTED_VLR_TEMPLATE";
export const SET_VLR_TEMPLATES = "SET_VLR_TEMPLATES";

export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const SET_TOTAL_STAR_BALANCE = "SET_TOTAL_STAR_BALANCE";

export const SET_SHARED_VOD_DATA = "SET_SHARED_VOD_DATA";
export const UPDATE_SHARED_VOD_DATA = "UPDATE_SHARED_VOD_DATA";
export const ADD_SHARED_VOD_DATA = "ADD_SHARED_VOD_DATA";
